vim.cmd('autocmd FileType python setlocal expandtab shiftwidth=4 softtabstop=4')
vim.cmd('autocmd FileType rust setlocal expandtab shiftwidth=4 softtabstop=4')
vim.cmd('autocmd FileType c,cpp,cuda setlocal expandtab shiftwidth=4 softtabstop=4')
vim.cmd('autocmd FileType sh setlocal expandtab shiftwidth=4 softtabstop=4')
vim.cmd('autocmd FileType lua setlocal expandtab shiftwidth=2 softtabstop=2')
vim.cmd('autocmd FileType markdown setlocal expandtab shiftwidth=2 softtabstop=2')
vim.cmd('autocmd FileType json setlocal expandtab shiftwidth=2 softtabstop=2')
